name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Step 3: Login to Heroku Container Registry
      - name: Heroku Docker Login
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      # Step 5: Push Docker image
      - name: Push Docker Image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Step 6: Release Docker image
      - name: Release Docker Image
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
